version: "3"
services:
  app:
    build: ./app
    ports:
      - 8080:8080
    tty: true
    stdin_open: true
    env_file:
      - ./env/app.env
    volumes:
      - type: bind
        source: ./app
        target: /app
  postgres:
    build: 
      dockerfile: ./db/Dockerfile
      args:
        - DB_LANG=ja_JP
    container_name: postgres
    ports:
      - "5432:5432"
    env_file:
      - ./env/db.env      
    volumes:
      - ./db:/var/lib/postgresql/data
      - ./db/etc/postgresql/15/main/pg_hba.conf:/etc/postgresql/15/main/pg_hba.conf
